import type {GoalReverseResult,GoalSettings,PortfolioSummary,Position,RiskStatus,Scenario,StressTestResult} from "./types";
export const calculateCurrentMarketValue=(p:Position)=>p.shares*p.currentPrice;
export const calculateFutureMarketValue=(p:Position,targetPrice=p.targetPrice)=>p.shares*targetPrice;
export const calculateEstimatedInterest=(p:Position)=>p.marginDebt*p.marginRate*p.holdingYears;
export const calculateCurrentEquity=(p:Position)=>calculateCurrentMarketValue(p)-p.marginDebt;
export const calculateFutureNetValue=(p:Position,targetPrice=p.targetPrice)=>calculateFutureMarketValue(p,targetPrice)-p.marginDebt-calculateEstimatedInterest(p);
export const calculateEquityRatio=(p:Position)=>calculateCurrentMarketValue(p)>0?calculateCurrentEquity(p)/calculateCurrentMarketValue(p):null;
export const calculateLeverageRatio=(p:Position)=>calculateCurrentEquity(p)>0?calculateCurrentMarketValue(p)/calculateCurrentEquity(p):null;
export const calculateDangerPrice=(p:Position)=>p.marginDebt>0&&p.shares>0&&p.maintenanceRequirement<1?p.marginDebt/((1-p.maintenanceRequirement)*p.shares):null;
export const scenarioPrice=(p:Position,s?:Scenario)=>s?.prices[p.ticker]??p.targetPrice;
export function riskStatus(p:Position,ratio=calculateEquityRatio(p)):RiskStatus{if(p.marginDebt===0)return"No Margin";if(ratio===null||ratio<p.maintenanceRequirement)return"Danger";if(ratio<p.maintenanceRequirement+.1)return"Warning";return"Safe"}
export function calculatePortfolioSummary(positions:Position[],scenario?:Scenario,target?:number):PortfolioSummary{const currentGrossValue=positions.reduce((a,p)=>a+calculateCurrentMarketValue(p),0);const totalMarginDebt=positions.reduce((a,p)=>a+p.marginDebt,0);const totalEstimatedInterest=positions.reduce((a,p)=>a+calculateEstimatedInterest(p),0);const futureGrossValue=positions.reduce((a,p)=>a+calculateFutureMarketValue(p,scenarioPrice(p,scenario)),0);const futureNetValue=positions.reduce((a,p)=>a+calculateFutureNetValue(p,scenarioPrice(p,scenario)),0);const rs=positions.map(p=>riskStatus(p));return{currentGrossValue,currentNetValue:currentGrossValue-totalMarginDebt,futureGrossValue,totalMarginDebt,totalEstimatedInterest,futureNetValue,goalProgress:target&&target>0?futureNetValue/target:undefined,portfolioRisk:rs.includes("Danger")?"High":rs.includes("Warning")?"Medium":"Low"}}
export function calculateGoalReverse(positions:Position[],settings:GoalSettings):GoalReverseResult{const p=positions.find(x=>x.ticker===settings.selectedTickerForReverse)??positions[0];const futureNetWorth=calculatePortfolioSummary(positions,undefined,settings.targetNetWorth).futureNetValue;const shortfall=settings.targetNetWorth-futureNetWorth;const selectedTickerTargetPrice=p?.targetPrice??0;const selectedTickerCurrentPrice=p?.currentPrice??0;const additionalSharesNeeded=shortfall>0&&selectedTickerTargetPrice>0?Math.ceil(shortfall/selectedTickerTargetPrice):0;const additionalPurchaseValue=additionalSharesNeeded*selectedTickerCurrentPrice;const additionalDebt=settings.allowMarginForAdditionalShares?additionalPurchaseValue*settings.additionalMarginRatio:0;return{targetNetWorth:settings.targetNetWorth,futureNetWorth,shortfall,isGoalReached:shortfall<=0,selectedTicker:p?.ticker??"",selectedTickerCurrentPrice,selectedTickerTargetPrice,additionalSharesNeeded,additionalPurchaseValue,additionalCashNeeded:additionalPurchaseValue-additionalDebt,additionalDebt,projectedFutureNetWorthAfterAdding:futureNetWorth+additionalSharesNeeded*selectedTickerTargetPrice}}
export function calculateStressTest(position:Position,dropPercentages:number[]):StressTestResult[]{return dropPercentages.map(dropPercentage=>{const priceAfterDrop=position.currentPrice*(1-dropPercentage);const marketValue=position.shares*priceAfterDrop;const equity=marketValue-position.marginDebt;const equityRatio=marketValue>0?equity/marketValue:null;return{ticker:position.ticker,dropPercentage,priceAfterDrop,marketValue,equity,equityRatio,riskStatus:riskStatus(position,equityRatio)}})}
