"use client";
import {useEffect,useMemo,useState} from "react";
import {Bar,BarChart,CartesianGrid,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {calculateCurrentEquity,calculateCurrentMarketValue,calculateDangerPrice,calculateEquityRatio,calculateFutureNetValue,calculateGoalReverse,calculateLeverageRatio,calculatePortfolioSummary,calculateStressTest,riskStatus} from "@/lib/calculations";
import {demoGoalSettings,demoPositions,STORAGE_KEYS} from "@/lib/demo-data";
import {money,num,pct,price} from "@/lib/format";
import type {GoalSettings,Position,RiskStatus} from "@/lib/types";

const drops=[.1,.2,.3,.5,.7];
const blank:Position={id:"",ticker:"NEW",name:"新部位",shares:1,averageCost:0,currentPrice:1,targetPrice:1,marginDebt:0,marginRate:0,holdingYears:2,maintenanceRequirement:.25,category:"",note:""};
const toNum=(v:string)=>v===""?0:Number(v);
function load<T>(key:string,fallback:T){try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw) as T:fallback}catch{return fallback}}
function riskText(v:string){return({High:"高",Medium:"中",Low:"低",Danger:"危險",Warning:"警示",Safe:"安全","No Margin":"無融資"} as Record<string,string>)[v]??v}
function riskClass(v:string){return v==="High"||v==="Danger"?"border-rose-400/40 bg-rose-400/10 text-rose-100":v==="Medium"||v==="Warning"?"border-amber-400/40 bg-amber-400/10 text-amber-100":"border-emerald-400/40 bg-emerald-400/10 text-emerald-100"}
function rowErrors(p:Position){const e:string[]=[];const name=p.ticker||"未命名部位";if(!p.ticker.trim())e.push("股票代號不可為空");if(p.shares<=0)e.push(`${name}：股數必須大於 0`);if(p.currentPrice<=0)e.push(`${name}：目前股價必須大於 0`);if(p.targetPrice<=0)e.push(`${name}：目標價必須大於 0`);if(p.averageCost<0)e.push(`${name}：平均成本不可小於 0`);if(p.marginDebt<0)e.push(`${name}：融資借款不可小於 0`);if(p.marginDebt>calculateCurrentMarketValue(p))e.push(`${name}：融資借款不可大於目前市值`);if(p.marginRate<0)e.push(`${name}：融資利率不可小於 0`);if(p.holdingYears<0)e.push(`${name}：持有年數不可小於 0`);if(p.maintenanceRequirement<0||p.maintenanceRequirement>1)e.push(`${name}：維持率必須介於 0 到 1`);return e}
function settingErrors(s:GoalSettings){const e:string[]=[];if(s.targetNetWorth<=0)e.push("目標資產必須大於 0");if(s.additionalMarginRatio<0||s.additionalMarginRatio>1)e.push("新增部位融資比例必須介於 0 到 1");if(s.usdTwdRate<=0)e.push("美元兌台幣匯率必須大於 0");return e}
function Card({title,value,sub,tone}:{title:string;value:string;sub?:string;tone?:"blue"|"green"|"yellow"|"red"}){return <div className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><div className="text-sm text-slate-400">{title}</div><div className={`mt-2 text-2xl font-semibold ${tone==="blue"?"text-sky-200":tone==="green"?"text-emerald-200":tone==="yellow"?"text-amber-200":tone==="red"?"text-rose-200":"text-white"}`}>{value}</div>{sub&&<div className="mt-1 text-xs text-slate-500">{sub}</div>}</div>}
function N({value,onChange,w="w-24"}:{value:number;onChange:(v:number)=>void;w?:string}){return <input className={`${w} h-8 rounded border border-slate-700 bg-slate-950 px-2 text-sm text-slate-100`} type="number" step="any" value={value} onChange={e=>onChange(toNum(e.target.value))}/>}
function Badge({status}:{status:RiskStatus|string}){return <span className={`inline-flex rounded-md border px-2 py-1 text-xs font-medium ${riskClass(status)}`}>{riskText(status)}</span>}
export default function Home(){const[loaded,setLoaded]=useState(false);const[positions,setPositions]=useState<Position[]>(demoPositions);const[settings,setSettings]=useState<GoalSettings>(demoGoalSettings);const[showStress,setShowStress]=useState(false);
useEffect(()=>{setPositions(load(STORAGE_KEYS.positions,demoPositions));setSettings(load(STORAGE_KEYS.goalSettings,demoGoalSettings));setLoaded(true)},[]);
useEffect(()=>{if(loaded)localStorage.setItem(STORAGE_KEYS.positions,JSON.stringify(positions))},[loaded,positions]);useEffect(()=>{if(loaded)localStorage.setItem(STORAGE_KEYS.goalSettings,JSON.stringify(settings))},[loaded,settings]);
useEffect(()=>{if(!loaded)return;setSettings(s=>({...s,selectedTickerForReverse:positions.some(p=>p.ticker===s.selectedTickerForReverse)?s.selectedTickerForReverse:positions[0]?.ticker??""}))},[loaded,positions]);
const summary=useMemo(()=>calculatePortfolioSummary(positions,undefined,settings.targetNetWorth),[positions,settings.targetNetWorth]);const reverse=positions.length?calculateGoalReverse(positions,settings):null;const gap=settings.targetNetWorth-summary.futureNetValue;const errors=[...settingErrors(settings),...positions.flatMap(rowErrors)];
function update(id:string,patch:Partial<Position>){setPositions(xs=>xs.map(p=>p.id===id?{...p,...patch,ticker:patch.ticker!==undefined?patch.ticker.toUpperCase():p.ticker}:p))}
function add(){setPositions(xs=>[...xs,{...blank,id:crypto.randomUUID(),ticker:`NEW${xs.length+1}`}])}
function reset(){setPositions(demoPositions);setSettings(demoGoalSettings)}function clear(){setPositions([]);setSettings({...demoGoalSettings,selectedTickerForReverse:""})}
if(!loaded)return <main className="min-h-screen bg-slate-950 p-6 text-slate-100">載入中...</main>;
return <main className="min-h-screen bg-slate-950 text-slate-100"><div className="mx-auto max-w-7xl space-y-6 px-4 py-6"><header className="flex flex-col gap-3 border-b border-slate-800 pb-5 md:flex-row md:items-end md:justify-between"><div><p className="text-sm text-sky-300">單頁即時試算</p><h1 className="text-3xl font-semibold">買夠了嗎？投資部位反推試算器</h1></div><Badge status={summary.portfolioRisk}/></header>
<section className="grid gap-4 lg:grid-cols-[1fr_320px]"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card title="目標資產" value={money(settings.targetNetWorth,settings)}/><Card title="目前總市值" value={money(summary.currentGrossValue,settings)}/><Card title="目前總淨值" value={money(summary.currentNetValue,settings)}/><Card title="目標價推估淨資產" value={money(summary.futureNetValue,settings)} tone="blue"/><Card title="達成率" value={pct(summary.goalProgress??0)} sub="進度條顯示上限為 100%" tone={(summary.goalProgress??0)>=1?"green":"yellow"}/><Card title={gap>0?"距離目標":"超過目標"} value={money(Math.abs(gap),settings)} tone={gap>0?"yellow":"green"}/><Card title="總融資借款" value={money(summary.totalMarginDebt,settings)}/><Card title="預估融資利息" value={money(summary.totalEstimatedInterest,settings)}/></div><div className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><h2 className="font-semibold">全域設定</h2><label className="mt-3 block text-xs text-slate-300">目標資產<N value={settings.targetNetWorth} w="mt-1 w-full" onChange={v=>setSettings({...settings,targetNetWorth:v})}/></label><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs text-slate-300">顯示幣別<select className="mt-1 h-9 w-full rounded border border-slate-700 bg-slate-950 px-2" value={settings.currency} onChange={e=>setSettings({...settings,currency:e.target.value as "USD"|"TWD"})}><option value="USD">美元</option><option value="TWD">台幣</option></select></label><label className="text-xs text-slate-300">美元兌台幣<N value={settings.usdTwdRate} w="mt-1 w-full" onChange={v=>setSettings({...settings,usdTwdRate:v})}/></label></div><div className="mt-4 flex flex-wrap gap-2"><button className="rounded bg-slate-800 px-3 py-2 text-sm" onClick={reset}>還原範例</button><button className="rounded bg-rose-500 px-3 py-2 text-sm text-white" onClick={clear}>清空資料</button></div></div></section>
<section className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><div className="mb-2 flex justify-between text-sm"><span>目標進度</span><span>{pct(summary.goalProgress??0)}</span></div><div className="h-3 rounded-full bg-slate-800"><div className="h-3 rounded-full bg-sky-400" style={{width:`${Math.min(100,Math.max(0,(summary.goalProgress??0)*100))}%`}}/></div><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={[{name:"目前總市值",value:summary.currentGrossValue},{name:"目前總淨值",value:summary.currentNetValue},{name:"目標價淨值",value:summary.futureNetValue}]}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="name" stroke="#94a3b8"/><YAxis stroke="#94a3b8"/><Tooltip contentStyle={{background:"#020617",border:"1px solid #334155"}}/><ReferenceLine y={settings.targetNetWorth} stroke="#f59e0b"/><Bar dataKey="value" fill="#38bdf8" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></section>
{errors.length>0&&<section className="rounded-lg border border-rose-400/30 bg-rose-400/10 p-4 text-sm text-rose-100"><div className="mb-2 font-medium">請先修正以下欄位：</div>{errors.map(e=><div key={e}>{e}</div>)}</section>}
<section className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-lg font-semibold">部位即時編輯</h2><p className="text-sm text-slate-400">直接改表格裡的數字，上方資產、反推與風險會同步更新。</p></div><button className="rounded bg-sky-400 px-3 py-2 text-sm font-semibold text-slate-950" onClick={add}>新增部位</button></div>{positions.length===0?<div className="rounded border border-slate-800 p-6 text-sm text-slate-400">目前沒有任何部位。按「新增部位」開始試算。</div>:<div className="overflow-x-auto"><table className="w-full min-w-[1450px] border-collapse text-left text-sm"><thead><tr>{["股票代號","名稱","股數","平均成本","目前股價","目標價","融資借款","融資年利率","持有年數","維持率","目前市值","目標價淨值","風險","刪除"].map(h=><th className="border-b border-slate-800 bg-slate-950 px-3 py-3 text-xs text-slate-400" key={h}>{h}</th>)}</tr></thead><tbody>{positions.map(p=>{const st=riskStatus(p);return <tr key={p.id} className="[&_td]:border-b [&_td]:border-slate-800 [&_td]:px-3 [&_td]:py-3"><td><input className="h-8 w-24 rounded border border-slate-700 bg-slate-950 px-2 font-semibold" value={p.ticker} onChange={e=>update(p.id,{ticker:e.target.value})}/></td><td><input className="h-8 w-36 rounded border border-slate-700 bg-slate-950 px-2" value={p.name??""} onChange={e=>update(p.id,{name:e.target.value})}/></td><td><N value={p.shares} onChange={v=>update(p.id,{shares:v})}/></td><td><N value={p.averageCost} onChange={v=>update(p.id,{averageCost:v})}/></td><td><N value={p.currentPrice} onChange={v=>update(p.id,{currentPrice:v})}/></td><td><N value={p.targetPrice} onChange={v=>update(p.id,{targetPrice:v})}/></td><td><N value={p.marginDebt} onChange={v=>update(p.id,{marginDebt:v})}/></td><td><N value={p.marginRate} w="w-20" onChange={v=>update(p.id,{marginRate:v})}/></td><td><N value={p.holdingYears} w="w-20" onChange={v=>update(p.id,{holdingYears:v})}/></td><td><N value={p.maintenanceRequirement} w="w-20" onChange={v=>update(p.id,{maintenanceRequirement:v})}/></td><td>{money(calculateCurrentMarketValue(p),settings)}</td><td>{money(calculateFutureNetValue(p),settings)}</td><td><Badge status={st}/></td><td><button className="rounded bg-rose-500 px-3 py-2 text-xs text-white" onClick={()=>setPositions(xs=>xs.filter(x=>x.id!==p.id))}>刪除</button></td></tr>})}</tbody></table></div>}</section>
<section className="grid gap-5 lg:grid-cols-2"><div className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><h2 className="text-lg font-semibold">目標反推</h2><p className="text-sm text-slate-400">用某一檔股票的目標價來補足資產缺口。</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-300">用哪一檔補足缺口<select className="mt-1 h-9 w-full rounded border border-slate-700 bg-slate-950 px-2" value={settings.selectedTickerForReverse} onChange={e=>setSettings({...settings,selectedTickerForReverse:e.target.value})}>{positions.map(p=><option key={p.id} value={p.ticker}>{p.ticker}</option>)}</select></label><label className="text-xs text-slate-300">新增部位融資比例<N value={settings.additionalMarginRatio} w="mt-1 w-full" onChange={v=>setSettings({...settings,additionalMarginRatio:v})}/></label></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.allowMarginForAdditionalShares} onChange={e=>setSettings({...settings,allowMarginForAdditionalShares:e.target.checked})}/>允許新增股數使用融資</label>{reverse?<div className="mt-4 grid gap-3 sm:grid-cols-2"><Card title="未來淨資產" value={money(reverse.futureNetWorth,settings)}/><Card title={reverse.isGoalReached?"已超過目標":"目前缺口"} value={money(Math.abs(reverse.shortfall),settings)} tone={reverse.isGoalReached?"green":"yellow"}/><Card title="還需要買" value={`${num(reverse.additionalSharesNeeded)} 股`}/><Card title="需要投入" value={money(reverse.additionalPurchaseValue,settings)}/><Card title="自備款" value={money(reverse.additionalCashNeeded,settings)}/><Card title="新增融資借款" value={money(reverse.additionalDebt,settings)}/></div>:<div className="mt-4 text-sm text-slate-400">請先新增至少一筆股票部位。</div>}</div><div className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><h2 className="text-lg font-semibold">融資風險</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left text-sm"><thead><tr>{["股票","淨值","維持率","槓桿","危險價","狀態"].map(h=><th className="border-b border-slate-800 bg-slate-950 px-3 py-3 text-xs text-slate-400" key={h}>{h}</th>)}</tr></thead><tbody>{positions.map(p=>{const st=riskStatus(p);return <tr className="[&_td]:border-b [&_td]:border-slate-800 [&_td]:px-3 [&_td]:py-3" key={p.id}><td>{p.ticker}</td><td>{money(calculateCurrentEquity(p),settings)}</td><td>{pct(calculateEquityRatio(p)??NaN)}</td><td>{calculateLeverageRatio(p)?.toFixed(2)??"N/A"}</td><td>{calculateDangerPrice(p)?`$${price(calculateDangerPrice(p)??0)}`:"N/A"}</td><td><Badge status={st}/></td></tr>})}</tbody></table></div><button className="mt-4 rounded bg-slate-800 px-3 py-2 text-sm" onClick={()=>setShowStress(v=>!v)}>{showStress?"隱藏壓力測試":"顯示壓力測試"}</button></div></section>
{showStress&&<section className="rounded-lg border border-slate-800 bg-slate-900/70 p-4"><h2 className="text-lg font-semibold">下跌壓力測試</h2><p className="text-sm text-slate-400">測試股價下跌 10%、20%、30%、50%、70% 後的融資狀態。</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[980px] border-collapse text-left text-sm"><thead><tr>{["股票","跌幅","下跌後股價","市值","淨值","維持率","狀態"].map(h=><th className="border-b border-slate-800 bg-slate-950 px-3 py-3 text-xs text-slate-400" key={h}>{h}</th>)}</tr></thead><tbody>{positions.flatMap(p=>calculateStressTest(p,drops)).map(r=><tr className="[&_td]:border-b [&_td]:border-slate-800 [&_td]:px-3 [&_td]:py-3" key={`${r.ticker}-${r.dropPercentage}`}><td>{r.ticker}</td><td>-{pct(r.dropPercentage)}</td><td>${price(r.priceAfterDrop)}</td><td>{money(r.marketValue,settings)}</td><td>{money(r.equity,settings)}</td><td>{pct(r.equityRatio??NaN)}</td><td><Badge status={r.riskStatus}/></td></tr>)}</tbody></table></div></section>}
<footer className="border-t border-slate-800 pt-5 text-xs leading-6 text-slate-500">本工具僅供個人情境試算，不構成投資建議、財務建議或融資交易建議。實際融資條件、維持率與追繳規則會依券商、個股、帳戶類型與市場狀況而異。</footer></div></main>}
