"use client";
import {useEffect,useMemo,useState} from "react";
import {Bar,BarChart,CartesianGrid,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import {calculateCurrentEquity,calculateCurrentMarketValue,calculateDangerPrice,calculateEstimatedInterest,calculateFutureMarketValue,calculateFutureNetValue,calculateGoalReverse,calculateLeverageRatio,calculatePortfolioSummary,calculateStressTest,calculateEquityRatio,riskStatus,scenarioPrice} from "@/lib/calculations";
import {demoGoalSettings,demoPositions,demoScenarios,STORAGE_KEYS} from "@/lib/demo-data";
import {money,num,pct,price} from "@/lib/format";
import type {GoalSettings,Position,Scenario} from "@/lib/types";

type Tab="Dashboard"|"Positions"|"Scenarios"|"Goal Reverse"|"Margin Risk"|"Settings";
const tabs:Tab[]=["Dashboard","Positions","Scenarios","Goal Reverse","Margin Risk","Settings"];
const empty:Position={id:"",ticker:"",name:"",shares:0,averageCost:0,currentPrice:0,targetPrice:0,marginDebt:0,marginRate:0,holdingYears:0,maintenanceRequirement:.25,category:"",note:""};
const n=(v:string)=>v===""?0:Number(v);
function load<T>(k:string,f:T){try{const r=localStorage.getItem(k);return r?JSON.parse(r) as T:f}catch{return f}}
function badge(v:string){return `badge ${v==="High"||v==="Danger"?"danger":v==="Medium"||v==="Warning"?"warn":"safe"}`}
function validate(p:Position){const e:string[]=[];if(!p.ticker.trim())e.push("ticker 不可為空");if(p.shares<=0)e.push("shares 必須大於 0");if(p.currentPrice<=0)e.push("currentPrice 必須大於 0");if(p.targetPrice<=0)e.push("targetPrice 必須大於 0");if(p.averageCost<0)e.push("averageCost 不可小於 0");if(p.marginDebt<0)e.push("marginDebt 不可小於 0");if(p.marginDebt>calculateCurrentMarketValue(p))e.push("marginDebt 不可大於 currentMarketValue");if(p.marginRate<0)e.push("marginRate 不可小於 0");if(p.holdingYears<0)e.push("holdingYears 不可小於 0");if(p.maintenanceRequirement<0||p.maintenanceRequirement>1)e.push("maintenanceRequirement 必須介於 0 到 1");return e}
function Card({title,value,sub}:{title:string;value:string;sub?:string}){return <div className="card p-4"><div className="text-sm text-slate-400">{title}</div><div className="mt-2 text-2xl font-semibold text-white">{value}</div>{sub&&<div className="mt-1 text-xs text-slate-500">{sub}</div>}</div>}
function Field({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="space-y-1 text-xs text-slate-300">{label}<input className="input" type="number" step="any" value={value} onChange={e=>onChange(n(e.target.value))}/></label>}
export default function Home(){const[loaded,setLoaded]=useState(false);const[tab,setTab]=useState<Tab>("Dashboard");const[positions,setPositions]=useState<Position[]>(demoPositions);const[scenarios,setScenarios]=useState<Scenario[]>(demoScenarios);const[settings,setSettings]=useState<GoalSettings>(demoGoalSettings);const[form,setForm]=useState<Position>(empty);const[edit,setEdit]=useState<string|null>(null);const[errors,setErrors]=useState<string[]>([]);
useEffect(()=>{setPositions(load(STORAGE_KEYS.positions,demoPositions));setScenarios(load(STORAGE_KEYS.scenarios,demoScenarios));setSettings(load(STORAGE_KEYS.goalSettings,demoGoalSettings));setLoaded(true)},[]);
useEffect(()=>{if(loaded)localStorage.setItem(STORAGE_KEYS.positions,JSON.stringify(positions))},[loaded,positions]);useEffect(()=>{if(loaded)localStorage.setItem(STORAGE_KEYS.scenarios,JSON.stringify(scenarios))},[loaded,scenarios]);useEffect(()=>{if(loaded)localStorage.setItem(STORAGE_KEYS.goalSettings,JSON.stringify(settings))},[loaded,settings]);
useEffect(()=>{if(!loaded)return;setSettings(s=>({...s,selectedScenarioId:scenarios.some(x=>x.id===s.selectedScenarioId)?s.selectedScenarioId:scenarios[0]?.id??"",selectedTickerForReverse:positions.some(x=>x.ticker===s.selectedTickerForReverse)?s.selectedTickerForReverse:positions[0]?.ticker??""}))},[loaded,positions,scenarios]);
const scenario=scenarios.find(s=>s.id===settings.selectedScenarioId)??scenarios[0];const summary=useMemo(()=>calculatePortfolioSummary(positions,scenario,settings.targetNetWorth),[positions,scenario,settings.targetNetWorth]);const reverse=scenario&&positions.length?calculateGoalReverse(positions,scenario,settings):null;const scenarioRows=scenarios.map(s=>({name:s.name,...calculatePortfolioSummary(positions,s,settings.targetNetWorth)}));
function save(){const p={...form,id:edit??form.ticker.toLowerCase()??crypto.randomUUID(),ticker:form.ticker.trim().toUpperCase(),maintenanceRequirement:form.maintenanceRequirement||.25};const e=validate(p);setErrors(e);if(e.length)return;setPositions(xs=>edit?xs.map(x=>x.id===edit?p:x):[...xs,p]);setScenarios(xs=>xs.map(s=>({...s,prices:{...s.prices,[p.ticker]:p.targetPrice}})));setForm(empty);setEdit(null)}
function reset(){setPositions(demoPositions);setScenarios(demoScenarios);setSettings(demoGoalSettings)}function clear(){setPositions([]);setScenarios([]);setSettings({...demoGoalSettings,selectedScenarioId:"",selectedTickerForReverse:""})}
return <main className="min-h-screen bg-slate-950"><div className="mx-auto max-w-7xl space-y-6 px-4 py-6"><header className="flex flex-col gap-3 border-b border-slate-800 pb-5 md:flex-row md:items-end md:justify-between"><div><p className="text-sm text-sky-300">Portfolio Goal Reverse Calculator</p><h1 className="text-3xl font-semibold text-white">買夠了嗎？投資部位反推試算器</h1></div><span className={badge(summary.portfolioRisk)}>融資風險：{summary.portfolioRisk}</span></header><nav className="flex gap-2 overflow-x-auto">{tabs.map(t=><button className={`btn ${tab===t?"":"btn2"}`} key={t} onClick={()=>setTab(t)}>{t}</button>)}</nav>
{tab==="Dashboard"&&<section className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card title="目標資產" value={money(settings.targetNetWorth,settings)}/><Card title="目前總市值" value={money(summary.currentGrossValue,settings)}/><Card title="目前總淨值" value={money(summary.currentNetValue,settings)}/><Card title="未來推估淨資產" value={money(summary.futureNetValue,settings)}/><Card title="達成率" value={pct(summary.goalProgress??0)}/><Card title={(summary.goalProgress??0)>=1?"超過目標":"距離目標"} value={money(Math.abs(settings.targetNetWorth-summary.futureNetValue),settings)}/><Card title="總融資借款" value={money(summary.totalMarginDebt,settings)}/><Card title="總預估融資利息" value={money(summary.totalEstimatedInterest,settings)}/></div><div className="card p-4"><div className="mb-2 flex justify-between text-sm"><span>Goal Progress</span><span>{pct(summary.goalProgress??0)}</span></div><div className="h-3 rounded-full bg-slate-800"><div className="h-3 rounded-full bg-sky-400" style={{width:`${Math.min(100,Math.max(0,(summary.goalProgress??0)*100))}%`}}/></div></div><Chart rows={[{name:"Current Gross",value:summary.currentGrossValue},{name:"Current Net",value:summary.currentNetValue},{name:"Future Net",value:summary.futureNetValue}]} target={settings.targetNetWorth}/><PositionTable positions={positions} scenario={scenario} settings={settings} setForm={setForm} setEdit={setEdit} setTab={setTab} setPositions={setPositions}/></section>}
{tab==="Positions"&&<section className="grid gap-5 lg:grid-cols-[380px_1fr]"><div className="card space-y-3 p-4"><h2 className="text-lg font-semibold">{edit?"Edit":"Add"} Position</h2><label className="space-y-1 text-xs text-slate-300">Ticker<input className="input" value={form.ticker} onChange={e=>setForm({...form,ticker:e.target.value})}/></label><label className="space-y-1 text-xs text-slate-300">Name<input className="input" value={form.name??""} onChange={e=>setForm({...form,name:e.target.value})}/></label><div className="grid gap-3 sm:grid-cols-2"><Field label="Shares" value={form.shares} onChange={v=>setForm({...form,shares:v})}/><Field label="Average Cost" value={form.averageCost} onChange={v=>setForm({...form,averageCost:v})}/><Field label="Current Price" value={form.currentPrice} onChange={v=>setForm({...form,currentPrice:v})}/><Field label="Target Price" value={form.targetPrice} onChange={v=>setForm({...form,targetPrice:v})}/><Field label="Margin Debt" value={form.marginDebt} onChange={v=>setForm({...form,marginDebt:v})}/><Field label="Margin Rate" value={form.marginRate} onChange={v=>setForm({...form,marginRate:v})}/><Field label="Holding Years" value={form.holdingYears} onChange={v=>setForm({...form,holdingYears:v})}/><Field label="Maintenance Req." value={form.maintenanceRequirement} onChange={v=>setForm({...form,maintenanceRequirement:v})}/></div>{errors.length>0&&<div className="rounded border border-rose-500/40 bg-rose-500/10 p-3 text-sm text-rose-100">{errors.map(e=><div key={e}>{e}</div>)}</div>}<div className="flex gap-2"><button className="btn" onClick={save}>Save Position</button><button className="btn btn2" onClick={()=>{setForm(empty);setEdit(null)}}>Cancel</button></div><div className="flex gap-2"><button className="btn btn2" onClick={reset}>Reset Demo Data</button><button className="btn btn-danger" onClick={clear}>Clear All Data</button></div></div><PositionTable positions={positions} scenario={scenario} settings={settings} setForm={setForm} setEdit={setEdit} setTab={setTab} setPositions={setPositions}/></section>}
{tab==="Scenarios"&&<section className="space-y-5"><div className="card space-y-4 p-4"><h2 className="text-lg font-semibold">Scenario Price Editor</h2>{scenarios.map(s=><div className="grid gap-3 rounded border border-slate-800 p-3 md:grid-cols-[220px_1fr]" key={s.id}><input className="input" value={s.name} onChange={e=>setScenarios(xs=>xs.map(x=>x.id===s.id?{...x,name:e.target.value}:x))}/><div className="grid gap-3 sm:grid-cols-3">{positions.map(p=><Field key={p.id} label={p.ticker} value={s.prices[p.ticker]??p.targetPrice} onChange={v=>setScenarios(xs=>xs.map(x=>x.id===s.id?{...x,prices:{...x.prices,[p.ticker]:v}}:x))}/>)}</div></div>)}</div><Chart rows={scenarioRows.map(r=>({name:r.name,value:r.futureNetValue}))} target={settings.targetNetWorth}/><Table heads={["Scenario","Future Gross","Margin Debt","Interest","Future Net","Progress"]}>{scenarioRows.map(r=><tr key={r.name}><td>{r.name}</td><td>{money(r.futureGrossValue,settings)}</td><td>{money(r.totalMarginDebt,settings)}</td><td>{money(r.totalEstimatedInterest,settings)}</td><td>{money(r.futureNetValue,settings)}</td><td>{pct(r.goalProgress??0)}</td></tr>)}</Table></section>}
{tab==="Goal Reverse"&&<section className="grid gap-5 lg:grid-cols-[360px_1fr]"><div className="card space-y-3 p-4"><Field label="Target Net Worth" value={settings.targetNetWorth} onChange={v=>setSettings({...settings,targetNetWorth:v})}/><label className="space-y-1 text-xs text-slate-300">Scenario<select className="input" value={settings.selectedScenarioId} onChange={e=>setSettings({...settings,selectedScenarioId:e.target.value})}>{scenarios.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="space-y-1 text-xs text-slate-300">Ticker<select className="input" value={settings.selectedTickerForReverse} onChange={e=>setSettings({...settings,selectedTickerForReverse:e.target.value})}>{positions.map(p=><option key={p.id} value={p.ticker}>{p.ticker}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={settings.allowMarginForAdditionalShares} onChange={e=>setSettings({...settings,allowMarginForAdditionalShares:e.target.checked})}/>Allow Margin</label><Field label="Additional Margin Ratio" value={settings.additionalMarginRatio} onChange={v=>setSettings({...settings,additionalMarginRatio:v})}/>{(settings.targetNetWorth<=0||(settings.additionalMarginRatio<0||settings.additionalMarginRatio>1))&&<div className="text-sm text-rose-200">targetNetWorth 必須大於 0；additionalMarginRatio 必須介於 0 到 1</div>}</div>{reverse?<div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Card title="目前情境未來淨資產" value={money(reverse.futureNetWorth,settings)}/><Card title="目標資產" value={money(reverse.targetNetWorth,settings)}/><Card title={reverse.isGoalReached?"已超過目標":"缺口"} value={money(Math.abs(reverse.shortfall),settings)}/><Card title={`需補 ${reverse.selectedTicker} 股數`} value={num(reverse.additionalSharesNeeded)}/><Card title="需投入總金額" value={money(reverse.additionalPurchaseValue,settings)}/><Card title="自備款 / 新增借款" value={`${money(reverse.additionalCashNeeded,settings)} / ${money(reverse.additionalDebt,settings)}`}/></div><div className="card p-4 leading-7 text-slate-300">在 {scenario?.name} 情境下，你的未來淨資產為 {money(reverse.futureNetWorth,settings)}，目標資產為 {money(reverse.targetNetWorth,settings)}。若靠 {reverse.selectedTicker} 補足，目標價為 ${price(reverse.selectedTickerTargetPrice)}，還需要買 {num(reverse.additionalSharesNeeded)} 股。加碼後推估未來淨資產：{money(reverse.projectedFutureNetWorthAfterAdding,settings)}。</div></div>:<div className="card p-4">請先新增 position 與 scenario。</div>}</section>}
{tab==="Margin Risk"&&<section className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card title="總融資借款" value={money(summary.totalMarginDebt,settings)}/><Card title="總融資利息" value={money(summary.totalEstimatedInterest,settings)}/><Card title="整體槓桿倍數" value={summary.currentNetValue>0?`${(summary.currentGrossValue/summary.currentNetValue).toFixed(2)}x`:"N/A"}/><Card title="Portfolio Risk" value={summary.portfolioRisk}/></div><Table heads={["Ticker","Market Value","Equity","Equity Ratio","Leverage","Interest","Danger Price","Status"]}>{positions.map(p=>{const st=riskStatus(p);return <tr key={p.id}><td>{p.ticker}</td><td>{money(calculateCurrentMarketValue(p),settings)}</td><td>{money(calculateCurrentEquity(p),settings)}</td><td>{pct(calculateEquityRatio(p)??NaN)}</td><td>{calculateLeverageRatio(p)?.toFixed(2)??"N/A"}</td><td>{money(calculateEstimatedInterest(p),settings)}</td><td>{calculateDangerPrice(p)?`$${price(calculateDangerPrice(p)??0)}`:"N/A"}</td><td><span className={badge(st)}>{st}</span></td></tr>})}</Table><Table heads={["Ticker","Drop","Price After Drop","Market Value","Equity","Equity Ratio","Risk Status"]}>{positions.flatMap(p=>calculateStressTest(p,[.1,.2,.3,.5,.7])).map(r=><tr key={`${r.ticker}-${r.dropPercentage}`}><td>{r.ticker}</td><td>-{pct(r.dropPercentage)}</td><td>${price(r.priceAfterDrop)}</td><td>{money(r.marketValue,settings)}</td><td>{money(r.equity,settings)}</td><td>{pct(r.equityRatio??NaN)}</td><td><span className={badge(r.riskStatus)}>{r.riskStatus}</span></td></tr>)}</Table></section>}
{tab==="Settings"&&<section className="card max-w-xl space-y-3 p-4"><label className="space-y-1 text-xs text-slate-300">Currency<select className="input" value={settings.currency} onChange={e=>setSettings({...settings,currency:e.target.value as "USD"|"TWD"})}><option>USD</option><option>TWD</option></select></label><Field label="USD/TWD Rate" value={settings.usdTwdRate} onChange={v=>setSettings({...settings,usdTwdRate:v})}/><div className="flex gap-2"><button className="btn btn2" onClick={reset}>Reset Demo Data</button><button className="btn btn-danger" onClick={clear}>Clear All Data</button></div></section>}
<footer className="border-t border-slate-800 pt-5 text-xs leading-6 text-slate-500"><p>This tool is for personal scenario planning only. It does not provide investment advice, financial advice, or margin trading recommendations. Margin requirements may vary by broker, security, account type, and market condition.</p><p>本工具僅供個人情境試算，不構成投資建議、財務建議或融資交易建議。實際融資條件、維持率與追繳規則會依券商、個股、帳戶類型與市場狀況而異。</p></footer></div></main>}
function Chart({rows,target}:{rows:{name:string;value:number}[];target:number}){return <div className="card h-80 p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="name" stroke="#94a3b8"/><YAxis stroke="#94a3b8"/><Tooltip contentStyle={{background:"#020617",border:"1px solid #334155"}}/><ReferenceLine y={target} stroke="#f59e0b"/><Bar dataKey="value" fill="#38bdf8" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>}
function Table({heads,children}:{heads:string[];children:React.ReactNode}){return <div className="table-scroll card"><table className="w-full min-w-[900px] border-collapse text-left text-sm"><thead><tr>{heads.map(h=><th className="border-b border-slate-800 bg-slate-950 px-3 py-3 text-xs uppercase text-slate-400" key={h}>{h}</th>)}</tr></thead><tbody className="[&_td]:border-b [&_td]:border-slate-800 [&_td]:px-3 [&_td]:py-3">{children}</tbody></table></div>}
function PositionTable({positions,scenario,settings,setForm,setEdit,setTab,setPositions}:{positions:Position[];scenario?:Scenario;settings:GoalSettings;setForm:(p:Position)=>void;setEdit:(id:string)=>void;setTab:(t:Tab)=>void;setPositions:React.Dispatch<React.SetStateAction<Position[]>>}){return <Table heads={["Ticker","Shares","Current Price","Target Price","Current Value","Future Value","Margin Debt","Future Net Value","Risk Level","Actions"]}>{positions.map(p=>{const t=scenarioPrice(p,scenario);const st=riskStatus(p);return <tr key={p.id}><td><b>{p.ticker}</b><div className="text-xs text-slate-500">{p.name}</div></td><td>{num(p.shares)}</td><td>${price(p.currentPrice)}</td><td>${price(t)}</td><td>{money(calculateCurrentMarketValue(p),settings)}</td><td>{money(calculateFutureMarketValue(p,t),settings)}</td><td>{money(p.marginDebt,settings)}</td><td>{money(calculateFutureNetValue(p,t),settings)}</td><td><span className={badge(st)}>{st}</span></td><td><button className="btn btn2 mr-2" onClick={()=>{setForm(p);setEdit(p.id);setTab("Positions")}}>Edit</button><button className="btn btn-danger" onClick={()=>setPositions(xs=>xs.filter(x=>x.id!==p.id))}>Delete</button></td></tr>})}</Table>}
